TicTacToe Testing
OlukaDenis/TicTacToe-Javascript pull request #5
Opened 2020-05-21 21:14 UTC by OlukaDenis

- Testing the game functionalities

2020-05-22 13:43 UTC, bolah2009 requested changes
Awesome job with the tests!

Let's test all the public methods of each function used (`Gameboard` and `Player`).
   -   Each test examples should be testing the public method of `Gameboard`  (`checkWinner`, `getBoard`, `turn` and `reset`) and `Player` - (`name`, `marker`, `getMarker`, `setTurn`, `getTurn`, `getWins`, `setWin`)

#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-22 13:43 UTC, bolah2009 commented on test/index.test.js
> +import Player from '../src/modules/player';
[Optional]

Why not separate the tests into two files? This way you have a test file for `Gameboard` and `Player` separately.

2020-05-22 17:43 UTC, kalavhan commented
Hello @bolah2009, thank's a lot for the review, the test for the method getMarker() was missing, is now added and we modified the description of each test to be more descriptive.
Have a nice day!

2020-05-23 20:36 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-25 15:37 UTC, merged